# SPDX-License-Identifier: MIT
#
#  █████╗ ██████╗  █████╗ ███████╗
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝
# ███████║██████╔╝███████║███████╗
# ██╔══██║██╔══██╗██╔══██║╚════██║
# ██║  ██║██║  ██║██║  ██║███████║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
# Copyright (C) 2026 Riza Emre ARAS <r.emrearas@proton.me>
#
# Licensed under the MIT License.
# See LICENSE and THIRD_PARTY_LICENSES for details.
"""Export utilities — Markdown and JSON export for single conversation sessions."""

import json
from datetime import datetime
from typing import Any


def _to_blockquote(text: str) -> str:
    """Convert text to markdown blockquote format."""
    lines = text.split("\n")
    return "\n".join(f"> {line}" for line in lines)


def export_conversation_markdown(
    messages: list[dict[str, Any]], locale: str = "en"
) -> str:
    """
    Export conversation to formatted markdown.

    Args:
        messages: List of message dicts with role, content, sources, metadata.
        locale: Language for labels ('en' or 'tr').

    Returns:
        Formatted markdown string.
    """
    labels = {
        "tr": {
            "title": "EU AI Act RAG Sohbet Kaydı",
            "date": "Tarih",
            "total_messages": "Toplam Mesaj",
            "question": "Soru",
            "answer": "Yanıt",
            "sources": "Kaynaklar",
            "source": "Kaynak",
            "score": "Puan",
            "search_query": "Arama Sorgusu",
            "duration": "Süre",
            "metadata": "Metadata",
            "footer": "Bu dosya EU AI Act RAG Playground tarafından oluşturulmuştur.",
            "generated_at": "Oluşturulma Tarihi",
        },
        "en": {
            "title": "EU AI Act RAG Conversation Log",
            "date": "Date",
            "total_messages": "Total Messages",
            "question": "Question",
            "answer": "Answer",
            "sources": "Sources",
            "source": "Source",
            "score": "Score",
            "search_query": "Search Query",
            "duration": "Duration",
            "metadata": "Metadata",
            "footer": "This file was generated by EU AI Act RAG Playground.",
            "generated_at": "Generated At",
        },
    }

    l = labels.get(locale, labels["en"])
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    md = [
        f"# {l['title']}",
        "",
        f"**{l['date']}:** {now}  ",
        f"**{l['total_messages']}:** {len(messages)}  ",
        "",
        "---",
        "",
    ]

    question_num = 0
    for msg in messages:
        if msg["role"] == "user":
            question_num += 1
            md.append(f"## {l['question']} {question_num}")
            md.append("")
            md.append(msg["content"])
            md.append("")

        elif msg["role"] == "assistant":
            md.append(f"### {l['answer']}")
            md.append("")
            md.append(_to_blockquote(msg["content"]))
            md.append("")

            sources = msg.get("sources", [])
            if sources:
                md.append("<details>")
                md.append(
                    f"<summary>{l['sources']} ({len(sources)})</summary>"
                )
                md.append("")
                for src in sources:
                    score_pct = src["score"] * 100
                    md.append(
                        f"- **{src['filename']}** ({l['score']}: {score_pct:.1f}%)"
                    )
                    content = src.get("content", "")
                    if content:
                        md.append("")
                        md.append("```")
                        if len(content) > 2000:
                            md.append(f"{content[:2000]}\n... (truncated)")
                        else:
                            md.append(content)
                        md.append("```")
                        md.append("")
                md.append("</details>")
                md.append("")

            metadata = msg.get("metadata", {})
            if metadata:
                md.append("<details>")
                md.append(f"<summary>{l['metadata']}</summary>")
                md.append("")
                md.append(
                    f"- **{l['search_query']}:** {metadata.get('search_query', '-')}"
                )
                md.append(
                    f"- **{l['duration']}:** {metadata.get('duration_ms', 0)}ms"
                )
                md.append("")
                md.append("</details>")
                md.append("")

            md.append("---")
            md.append("")

    md.append(f"_{l['footer']}_  ")
    md.append(f"_{l['generated_at']}: {now}_")

    return "\n".join(md)


def export_conversation_json(messages: list[dict[str, Any]]) -> str:
    """
    Export conversation to JSON format.

    Args:
        messages: List of message dicts with role, content, sources, metadata.

    Returns:
        JSON string.
    """
    export_data = {
        "metadata": {
            "total_messages": len(messages),
            "exported_at": datetime.now().isoformat(),
        },
        "conversations": [],
    }

    for i, msg in enumerate(messages):
        entry = {
            "index": i,
            "role": msg["role"],
            "content": msg["content"],
        }

        if msg.get("sources"):
            entry["sources"] = msg["sources"]

        if msg.get("metadata"):
            entry["search_metadata"] = msg["metadata"]

        export_data["conversations"].append(entry)

    return json.dumps(export_data, ensure_ascii=False, indent=2)


def get_export_filename(extension: str) -> str:
    """
    Generate a filename for the export.

    Args:
        extension: File extension ('md' or 'json').

    Returns:
        Filename string.
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    return f"eu-ai-act-rag-conversation-{date_str}.{extension}"
